spring.profiles.active=local
server.servlet.context-path=/admin
server.port=8082
# Application
app.cors.allowed-origins=http://localhost:3000,http://localhost:4200
#database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/petneeds?useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.transaction.default-timeout=9999999
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#hibernate dialect is MariaDBDialect by default
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=catalog
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=100
#Asset configuration
pet.care.asset.dir.base=pet/care/dev/media/
#pet.care.asset.base-url=https://s3.us-east-2.amazonaws.com/pet-care-dev-test/
pet.care.asset.assets.base-url=~/asset/
#virtual threads configuration
spring.threads.virtual.enabled=true
#database pool configuration
spring.datasource.hikari.maximum-pool-size=20
# Elasticsearch Configuration
#elasticsearch.host=elasticsearch
#elasticsearch.port=9200
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.connection-timeout=1
spring.elasticsearch.socket-timeout=30
# Elasticsearch Logging Configuration
logging.level.org.springframework.data.elasticsearch=DEBUG
logging.level.com.petcare.common.elasticsearch=DEBUG
# Swagger Configuration
# Change swagger UI path
springdoc.swagger-ui.path=/docs
# Disable swagger in production
springdoc.swagger-ui.enabled=true
# Sort endpoints
springdoc.swagger-ui.operationsSorter=method
# JWT Configuration
jwt.secret=87ab465cbb15dae140e01f7e657b9f4fa9f87d70fa4efe1eeccb769fb23c67fd9bbe74207b6bb95c29c9059d2fc3ae3c96e151b5c56009f1e9ab0e6e44485936
# 150 minutes
jwt.access-token-expiration=150
#300 days
jwt.refresh-token-expiration=300
# Redis
data.redis.host=localhost
data.redis.port=6379
# leave empty if no password
data.redis.password=
data.redis.timeout=60000